<?php header('Content-Type: text/html; charset=utf-8'); ?>
<?php $content=$this->content;?>
<div id="message">
<div id="head">
    <label id="subject"><?php echo $content["subject"];?> </label>
    <label id="time"><?php echo $content["time"];   ?> </label><br>
    <label id="from"><?php echo $content["from"];?> </label>
    
       
</div>
    <div id="content"><?php echo $content["content"];?> </div>
</div>

